# Generated by Django 3.1.4 on 2020-12-26 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('statline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('fgm', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('fg3m', models.IntegerField(default=0)),
                ('fg3a', models.IntegerField(default=0)),
                ('ftm', models.IntegerField(default=0)),
                ('fta', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
                ('reb', models.IntegerField(default=0)),
                ('ast', models.IntegerField(default=0)),
                ('stl', models.IntegerField(default=0)),
                ('blk', models.IntegerField(default=0)),
                ('tov', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.players')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
