# Generated by Django 3.1.4 on 2020-12-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201227_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('league_id', models.CharField(max_length=10)),
                ('priv', models.BooleanField()),
                ('espn_s2', models.CharField(max_length=400)),
                ('swid', models.CharField(max_length=40)),
            ],
        ),
    ]
