# Generated by Django 3.1.4 on 2020-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_leagues'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.IntegerField()),
                ('mins', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fg3m', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=4)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'league_averages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('tricode', models.CharField(max_length=3, null=True)),
                ('conference', models.CharField(max_length=4, null=True)),
                ('division', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
