# Generated by Django 3.1.4 on 2020-12-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_leagueaverage_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonAverages',
        ),
    ]
