# Generated by Django 3.1.4 on 2020-12-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_seasonaverages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonAverages',
        ),
    ]
