# Generated by Django 3.1.4 on 2020-12-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_games_seasonaverages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leagues',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='LeagueAverage',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='SeasonAverages',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
