# Generated by Django 3.1.4 on 2020-12-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_auto_20201228_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5)),
                ('game_id', models.CharField(max_length=15)),
                ('game_date', models.DateField(null=True)),
                ('home_id', models.IntegerField(default=0)),
                ('visitor_id', models.IntegerField(default=0)),
                ('mins', models.IntegerField(default=0)),
                ('fgm', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('fg3m', models.IntegerField(default=0)),
                ('fg3a', models.IntegerField(default=0)),
                ('ftm', models.IntegerField(default=0)),
                ('fta', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
                ('off_reb', models.IntegerField(default=0)),
                ('def_reb', models.IntegerField(default=0)),
                ('tot_reb', models.IntegerField(default=0)),
                ('ast', models.IntegerField(default=0)),
                ('stl', models.IntegerField(default=0)),
                ('blk', models.IntegerField(default=0)),
                ('tov', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeagueAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mins', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fg3m', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=4)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'league_averages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('jersey', models.CharField(max_length=2)),
                ('years_pro', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.IntegerField()),
                ('mins', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fgpct', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ftpct', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fg3m', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=4)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'season_averages_9cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('tricode', models.CharField(max_length=3, null=True)),
                ('conference', models.CharField(max_length=4, null=True)),
                ('division', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('league_id', models.CharField(max_length=10)),
                ('priv', models.BooleanField()),
                ('espn_s2', models.CharField(max_length=400)),
                ('swid', models.CharField(max_length=40)),
            ],
        ),
    ]
