# Generated by Django 3.1.4 on 2020-12-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_games_leagueaverage_leagues_players_seasonaverages_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPNPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.players')),
            ],
        ),
        migrations.CreateModel(
            name='ESPNTeams',
            fields=[
                ('team_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abrv', models.CharField(max_length=4)),
                ('division_name', models.CharField(max_length=25)),
                ('logo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Leagues',
        ),
        migrations.AddField(
            model_name='espnplayers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.espnteams'),
        ),
    ]
