# Generated by Django 3.1.4 on 2020-12-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='espnteams',
            name='league_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
