# Generated by Django 3.1.4 on 2021-01-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_standarddeviations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPNLeagues',
            fields=[
                ('league_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('priv', models.BooleanField()),
                ('espn_s2', models.CharField(max_length=400)),
                ('swid', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='espnteams',
            name='league_id',
        ),
        migrations.AddField(
            model_name='espnteams',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.espnleagues'),
            preserve_default=False,
        ),
    ]
