# Generated by Django 3.1.4 on 2021-01-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_leagueaveragestandarddeviation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leagueaveragestandarddeviation',
            table='league_average_stddev',
        ),
    ]
